
before_script:
  - ./spec/dummy_32/script/setup

notifications:
  disable: true

language: ruby

rvm:
  - 1.9.3
  - 2.1.10
  - 2.2.7
  - 2.3.4
  - 2.4.1
  - ree
  #- ruby-head

gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails51.gemfile

matrix:
  include:
    - rvm: ree
      gemfile: gemfiles/rails32.187-ree.gemfile
  exclude:
    - rvm: ree
      gemfile: gemfiles/rails32.gemfile
  allow_failures:
    - rvm: ree
      gemfile: gemfiles/rails40.gemfile

services:
  - mongodb
