
before_script:
  - ./spec/dummy_32/script/setup

notifications:
  disable: true

language: ruby

rvm:
  - 1.9.3
  - 1.8.7
  - 2.0.0
  - ree
  #- ruby-head

gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile

matrix:
  allow_failures:
    - rvm: 1.8.7
      gemfile: gemfiles/rails40.gemfile
    - rvm: ree
      gemfile: gemfiles/rails40.gemfile

services:
  - mongodb
