# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rails_exception_handler}
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Sharagoz"]
  s.date = %q{2011-07-06}
  s.description = %q{}
  s.email = %q{contact@sharagoz.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENCE",
    "README.markdown",
    "Rakefile",
    "VERSION",
    "app/controllers/error_response_controller.rb",
    "app/models/error_message.rb",
    "lib/patch/show_exceptions.rb",
    "lib/rails_exception_handler.rb",
    "lib/rails_exception_handler/configuration.rb",
    "lib/rails_exception_handler/handler.rb",
    "lib/rails_exception_handler/parser.rb",
    "rails_exception_handler.gemspec",
    "spec/exception_handler_test_app/.gitignore",
    "spec/exception_handler_test_app/Gemfile",
    "spec/exception_handler_test_app/Gemfile.lock",
    "spec/exception_handler_test_app/Rakefile",
    "spec/exception_handler_test_app/app/controllers/application_controller.rb",
    "spec/exception_handler_test_app/app/controllers/home_controller.rb",
    "spec/exception_handler_test_app/app/helpers/application_helper.rb",
    "spec/exception_handler_test_app/app/models/stored_exception.rb",
    "spec/exception_handler_test_app/app/views/home/view_error.html.erb",
    "spec/exception_handler_test_app/app/views/layouts/application.html.erb",
    "spec/exception_handler_test_app/app/views/layouts/home.html.erb",
    "spec/exception_handler_test_app/config.ru",
    "spec/exception_handler_test_app/config/application.rb",
    "spec/exception_handler_test_app/config/boot.rb",
    "spec/exception_handler_test_app/config/environment.rb",
    "spec/exception_handler_test_app/config/environments/development.rb",
    "spec/exception_handler_test_app/config/environments/production.rb",
    "spec/exception_handler_test_app/config/environments/test.rb",
    "spec/exception_handler_test_app/config/examples/database.yml",
    "spec/exception_handler_test_app/config/initializers/rails_exception_handler.rb",
    "spec/exception_handler_test_app/config/locales/en.yml",
    "spec/exception_handler_test_app/config/routes.rb",
    "spec/exception_handler_test_app/db/migrate/20110630174538_create_error_messages.rb",
    "spec/exception_handler_test_app/db/migrate/20110702131654_add_sessions_table.rb",
    "spec/exception_handler_test_app/db/schema.rb",
    "spec/exception_handler_test_app/db/seeds.rb",
    "spec/exception_handler_test_app/lib/tasks/.gitkeep",
    "spec/exception_handler_test_app/script/rails",
    "spec/exception_handler_test_app/script/setup",
    "spec/exception_handler_test_app/vendor/plugins/.gitkeep",
    "spec/handler_spec.rb",
    "spec/integration_spec.rb",
    "spec/parser_spec.rb",
    "spec/spec_helper.rb",
    "spec/test_macros.rb"
  ]
  s.homepage = %q{http://github.com/Sharagoz/rails_exception_handler}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Exception Handling for Rails 3}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

